bundler_args: --without development --retry=3 --jobs=3
cache: bundler
language: ruby
rvm:
  - jruby-9.0.5.0
  - jruby-9.1.7.0
  - ruby-head
  - ruby-head-clang
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
matrix:
  include:
    - gemfile: gemfiles/Gemfile.public_suffix_2
      rvm: 2.5.0
  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang
  fast_finish: true
before_install:
  - gem update bundler
#   - apt-get update
#   - apt-get install idn
sudo: false
